services:
  # Backend API service
  - type: web
    name: orange-directory-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://babrawitch001:ErxixIg6YcxO703A@cluster0.bolrdly.mongodb.net/orange-directory?retryWrites=true&w=majority&appName=Cluster0

  # Frontend static site
  - type: static
    name: orange-directory-frontend
    buildCommand: echo "No build step needed for static site"
    publishDir: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: orange-directory-db
    databaseName: orange-directory
    plan: free
