services:
  # Combined frontend and backend service
  - type: web
    name: orange-directory
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://daejimyung:gxo9ubmEtTNllzzs@cluster0.ptct7mp.mongodb.net/orange-directory?retryWrites=true&w=majority&appName=Cluster0

  # Frontend static site
  - type: web
    name: orange-directory-frontend
    env: static
    buildCommand: npm install
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: orange-directory-db
    databaseName: orange-directory
    plan: free
