services:
  # Backend API service
  - type: web
    name: orange-directory-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: orange-directory-db
          property: connectionString

  # Frontend static site
  - type: web
    name: orange-directory-frontend
    env: static
    buildCommand: echo "No build step needed for static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: orange-directory-db
    databaseName: orange-directory
    plan: free
